_BASE_: "Base-CIS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  OSFormer:
    QS:
      NUM_MASKS: 20
SOLVER:
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00005